### PR TITLE
feat: update ollama to 0.2.8

### PR DESCRIPTION
**Pull request by TimPietrusky**
## Description

* Update ollama to 0.2.8 to get support for Llama 3.1

### CODE REVIEW

**Comment by TimPietrusky** [comment]
@pooyahrtn Is there anything else I need to do in order to get this working? Some tests that I can execute?

**Comment by pooyahrtn** [comment]
@TimPietrusky Thanks!

> Some tests that I can execute? 

For now, we need to test that manually. I need to document the local setup properly, but overall, you need to create and test a local docker image.

I'm mostly concerned about [this part](https://github.com/pooyahrtn/RunpodOllama/blob/main/server/start.sh#L7C1-L8C1) where it listens to the Ollama's log to indicate whether it's booted or not.

Once we're sure the docker image is working, I can take care of publishing it.

**Comment by TimPietrusky** [comment]
@pooyahrtn so just execute this locally and then run the image? 

```
cd server
docker build -t pooyaharatian/runpod-ollama:dev --platform linux/amd64 .
```

Anything else besides this?

**Comment by pooyahrtn** [comment]
@TimPietrusky I changed the Dockerfile locally and ran this. In your log, after "pulling manifest" you should see something like:

```
DEBUG  | local_test | Handler output: {'model': 'phi3', 'created_at': '2024-07-24T15:16:20.183010308Z', 'response': '', 'done': True, 'done_reason': 'load'}
DEBUG  | local_test | run_job return: {'output': {'model': 'phi3', 'created_at': '2024-07-24T15:16:20.183010308Z', 'response': '', 'done': True, 'done_reason': 'load'}}
INFO   | Job local_test completed successfully.
INFO   | Job result: {'output': {'model': 'phi3', 'created_at': '2024-07-24T15:16:20.183010308Z', 'response': '', 'done': True, 'done_reason': 'load'}}
INFO   | Local testing complete, exiting.
```

I published the `pooyaharatian/runpod-ollama:0.0.8` with your change. To test, you can change the `cli` file's docker-image (pooyaharatian/runpod-ollama:0.0.7) to `0.0.8` and see if it actually works with Runpod.

If it worked, can you update the `cli` file as well? Thanks!

**Comment by pooyahrtn** [comment]
I think it works. I tried with `llama3`. Here are the steps:
1. run `runpod-ollama create-model llama3 10`: This will create a `llama3` model with the latest image tag.
2. Go to the "Edit Endpoint" and assign a GPU
3. run `runpod-ollama start-proxy` to proxy the requests
4. curl the local proxy: 
```
curl -H "Content-Type: application/json" \                     44s  migration-agent
http://127.0.0.1:5001/<your pod id>/api/generate -d '{ 
"model": "llama3",
"prompt": "Why is the sky blue?",
"stream": false
}'
```

**Comment by TimPietrusky** [comment]
@pooyahrtn just to understand this: The "cli" file is just for convenience right? When I want to interact with RunPod using the UI, I can just use the image directly. Or is there anything that I'm missing here? 

And of course I will update that file as well.

**Comment by pooyahrtn** [comment]
@TimPietrusky indeed, it mostly abstracts calling the runpod endpoints and running the local (proxy) server.

**Comment by TimPietrusky** [comment]
@pooyahrtn 

* The CLI version of the image was updated
* I tested the image on RunPod with Llama 3.1 8B and it's working

Do you have time to work on this project further? Because then I'm happy to help out and improve it.

**Comment by pooyahrtn** [comment]
@TimPietrusky Thanks a lot! 

> Do you have time to work further on this project? Because then I'm happy to help out and improve it.

I have some spare time to work on this. At least, I'd help out with any contributions. Thanks again!

**Comment by TimPietrusky** [comment]
@pooyahrtn awesome, thank you!

**Pull request merged**
